# Generated by Django 3.1.3 on 2021-03-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_amount_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amount',
            name='user',
        ),
    ]
